pipeline {
  agent none
  stages {
    stage('Build') {
      agent { 
				docker { 
					image 'python:2-alpine' 
				} 
		  }
      steps {
		  		dir('hello-world-python'){  
					sh 'python -m py_compile sources/add2vals.py sources/calc.py' 
				}
			}
    }
    stage('Test') {
			agent { 
				docker { 
					image 'qnib/pytest' 
				} 
		  }
      steps {
		  		dir('hello-world-python'){  
					sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
				}
			}
		}
		stage('Deliver') {
			agent { 
				docker { 
					image 'cdrx/pyinstaller-linux:python2' 
		  	} 
			}
			steps {
				dir('hello-world-python'){  
					sh 'pyinstaller --onefile sources/add2vals.py'
				}
			}
			post {
				success {
			 		archiveArtifacts 'dist/add2vals'
				}
			}
		}
	}
}